### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.tools.api'

### ISSUE THREAD

**Issue by jishuanxu** [William9Baker/EfficientNet_based_on_Transfer_Learning#1]
作者你好，我安装的tensorflow-gpu1.12.0，keras2.2.4，但是运行代码报了如下错误，这是为什么呢
shuan@win-SYS-7048GR-TR:~/EfficientNet$ python training_efficientnet_with_transfer_learning.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "training_efficientnet_with_transfer_learning.py", line 12, in <module>
    from tensorflow.tools.api.generator.api.keras import models
ModuleNotFoundError: No module named 'tensorflow.tools.api'

**Comment by William9Baker** [comment]
因为缺少库
